apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-persistent-volume-claim
spec:
    #tells k8 hey find a storage with type ReadWriteOnce and space 2Gigs
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
